apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mdw20-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mdw20-app
    spec:
      containers:
        - name: mdw20-app
          image: payxdemo.azurecr.io/mdw20-app
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-shared-secrets
                  key: admin-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret-encoded
                  key: mongo-password-encoded
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: region-map
                  key: region