apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: visweshwarmdwApp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: visweshwarmdwApp
    spec:
      containers:
        - name: visweshwarmdwApp
          image: mdw20payxregistry.azurecr.io/visweshwarmdw
          ports:
            - containerPort: 8080
