apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mdw20-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mdw20-app
    spec:
      containers:
        - name: mdw20-app
          image: payxdemo.azurecr.io/mdw20-app
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-username
                  key: admin-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: admin-password