---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  labels:
    app: DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: DEPLOYMENT_NAME
    spec:
      containers:
      - name: mongos
        image: payxdemo.azurecr.io/mongodb-enterprise:55
        command:
          - mongos
          - --configdb
          - CONFIG_REPLICA_SET_NAME/CONFIG_REPLICA_SET_MEMBERS
          - --port
          - "MONGOS_PORT"
          - --bind_ip_all
          - --tlsMode
          - disabled
          - --noauth
        ports:
          - containerPort: MONGOS_PORT
            name: mongo
